// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MealVault.Entities
{
    public partial class FavoriteMeal
    {
        public int ID { get; set; }
        public int MealID { get; set; }
        public string Username { get; set; }
    }
}