// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MealVault.Entities
{
    public partial class User
    {
        public int ID { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Username { get; set; }
        public string MobileNumber { get; set; }
        public string Password { get; set; }
        public string Salt { get; set; }
    }
}